import "./styles.css";import {sampleProject} from "./data";import {parseEventsJsonl} from "./events";import {nextStage,stageProgress} from "./workflow";import type {MiaEvent,Project} from "./types";import {WORKFLOW_STAGES} from "./types";
let project:Project=structuredClone(sampleProject);let notice="";const app=document.querySelector<HTMLDivElement>("#app")!;
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));
const relative=(t:string)=>{const m=Math.max(1,Math.round((Date.now()-new Date(t).getTime())/60000));if(m<60)return m+"m ago";const h=Math.round(m/60);if(h<24)return h+"h ago";return Math.round(h/24)+"d ago"};
const recommendation=(s:Project["stage"])=>({intent:"Clarify the problem and definition of done",grill:"Turn assumptions into explicit constraints",plan:"Create verifiable implementation steps",execute:"Implement the smallest coherent change",review:"Check correctness, tests, and maintainability",ship:"Run verification before creating the PR",learn:"Capture the durable lesson from this cycle"}[s]);
function render(){const p=stageProgress(project.stage);app.innerHTML=`<main class="shell"><header class="topbar"><div><div class="eyebrow">MIA LENS</div><h1>${esc(project.name)}</h1><div class="repo">${esc(project.repo)} <span>·</span> <strong>${esc(project.branch)}</strong></div></div><div class="actions"><span class="pill healthy">${project.status}</span><button id="import" class="button secondary">Import events.jsonl</button><input id="file" type="file" accept=".jsonl,application/json" hidden><button id="cycle" class="button primary">Run cycle</button></div></header>${notice?`<div class="notice" role="status">${esc(notice)}</div>`:""}<section class="hero-grid"><article class="card"><div class="card-head"><span>Current work loop</span><span>${Math.round(p)}%</span></div><div class="stage-title"><span class="dot"></span>${project.stage}</div><div class="progress" role="progressbar" aria-label="Workflow progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(p)}"><span style="width:${p}%"></span></div><div class="workflow">${WORKFLOW_STAGES.map(s=>`<span class="${s===project.stage?"active":WORKFLOW_STAGES.indexOf(s)<WORKFLOW_STAGES.indexOf(project.stage)?"done":""}">${s}</span>`).join("")}</div><div class="mock-note">Deterministic demo execution. No model is called.</div></article><article class="card"><div class="card-head"><span>Next recommended action</span><span class="mono">MIA</span></div><h2>${esc(recommendation(project.stage))}</h2><p>Advance one explicit stage, verify the state, then record what was learned.</p></article></section><section class="grid-two"><article class="card"><div class="card-head"><span>Repository health</span><span class="count">${project.health.length}</span></div><div class="health-list">${project.health.map(i=>`<div class="health-row"><span class="status ${i.status}" aria-hidden="true"></span><div><strong>${esc(i.label)}</strong><small>${esc(i.detail)}</small></div></div>`).join("")}</div></article><article class="card"><div class="card-head"><span>Learnings</span><span class="count">${project.learnings.length}</span></div><div class="learning-list">${project.learnings.map(i=>`<div class="learning">↳ ${esc(i)}</div>`).join("")}</div></article></section><section class="card timeline-card"><div class="card-head"><span>Recent timeline</span><span class="count">${project.events.length} events</span></div><div class="timeline">${project.events.map(e=>`<div class="event"><div class="event-marker" aria-hidden="true"></div><div class="event-main"><div class="event-meta"><span>${esc(e.type)}</span><time>${relative(e.timestamp)}</time></div><strong>${esc(e.title)}</strong><p>${esc(e.detail)}</p></div></div>`).join("")}</div></section></main>`;
document.querySelector<HTMLButtonElement>("#cycle")?.addEventListener("click",runCycle);const ib=document.querySelector<HTMLButtonElement>("#import")!,fi=document.querySelector<HTMLInputElement>("#file")!;ib.addEventListener("click",()=>fi.click());fi.addEventListener("change",()=>void importEvents(fi));}
function runCycle(){const next=nextStage(project.stage);const e:MiaEvent={id:crypto.randomUUID(),timestamp:new Date().toISOString(),type:"workflow",title:`Advanced to ${next}`,detail:"Deterministic demo transition. No external agent or model was invoked.",stage:next,status:"info"};project={...project,stage:next,events:[e,...project.events].slice(0,12)};notice=`Demo cycle advanced to ${next}.`;render()}
async function importEvents(input:HTMLInputElement){const file=input.files?.[0];if(!file)return;try{const events=parseEventsJsonl(await file.text());const stage=[...events].reverse().find(e=>e.stage)?.stage??project.stage;project={...project,events,stage};notice=`Imported ${events.length} events locally. Nothing was uploaded.`}catch(e){notice=e instanceof Error?e.message:"Could not import events."}render()}
render();